# Generated by Django 4.2.15 on 2024-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='IMG/main.png', verbose_name='Изображение'),
        ),
    ]
