# Generated by Django 4.2.15 on 2024-09-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='item',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
    ]
